### ISSUE TITLE
Make the Background color of line numbers slightly different to the background color of the tex

### ISSUE THREAD

**Issue by mogoh** [atom/atom-light-syntax#14]
### Prerequisites

* [X] Put an X between the brackets on this line if you have done all of the following:
    * Reproduced the problem in Safe Mode: http://flight-manual.atom.io/hacking-atom/sections/debugging/#using-safe-mode
    * Followed all applicable steps in the debugging guide: http://flight-manual.atom.io/hacking-atom/sections/debugging/
    * Checked the FAQs on the message board for common solutions: https://discuss.atom.io/c/faq
    * Checked that your issue isn't already filed: https://github.com/issues?utf8=✓&q=is%3Aissue+user%3Aatom
    * Checked that there is not already an Atom package that provides the described functionality: https://atom.io/packages

### Description

It is hard to see if a line starts with a space or not because the background is plain white. Please change it (e.g. make the background of the line numbers light grey) so I can see if a line starts with a space or not.

### Steps to Reproduce

1. Load Atom Light Syntax
2. Add a whitespace to a Line of code
3. Ask someone else if the line starts with a whitespace or not. He probably would not be able to see it.

**Expected behavior:** [What you expect to happen]

**Actual behavior:** [What actually happens]

**Reproduces how often:** [What percentage of the time does it reproduce?]

### Versions

$ atom --version
Atom    : 1.15.0
Electron: 1.3.13
Chrome  : 52.0.2743.82
Node    : 6.5.0

OS: Lubuntu 17.04

### Additional Information

Any additional information, configuration or data that might be necessary to reproduce the issue.

**Comment by simurai** [comment]
Closing as `wontfix`. Here some workarounds for the "It is hard to see if a line starts with a space" problem:

## 1. 

Enable "indent guide" which gives a hint if there is an empty space at the beginning: 

![gutter](https://user-images.githubusercontent.com/378023/44560441-c0fe0b00-a78a-11e8-8569-e420653507cc.gif)

## 2. 

Toggle "invisibles" on.

![image](https://user-images.githubusercontent.com/378023/44560780-5352de80-a78c-11e8-913c-9492452541d1.png)

## 3. 

Customize the gutter background in your [styles.less](http://flight-manual.atom.io/using-atom/sections/basic-customization/#style-tweaks) file. Like proposed in this issue. For example:

```less
atom-text-editor .gutter {
  background-color: #efefef;
}
```
👇 

![screen shot 2018-08-24 at 10 49 59 am](https://user-images.githubusercontent.com/378023/44560611-8f397400-a78b-11e8-92e5-902a835c5478.png)
